export const wordsByDifficulty = {
easy: [
  {word:"apple", hint:"A popular fruit"},
  {word:"chair", hint:"You sit on it"},
  {word:"water", hint:"You drink it"},
  {word:"train", hint:"Transport on rails"},
  {word:"mouse", hint:"Used with a computer"},
  {word:"table", hint:"Furniture with legs"},
  {word:"happy", hint:"Opposite of sad"},
  {word:"house", hint:"Place to live"},
  {word:"light", hint:"Opposite of dark"},
  {word:"smile", hint:"Happiness expression"},
  {word:"green", hint:"Color of nature"},
  {word:"stone", hint:"Hard natural material"},
  {word:"sweet", hint:"Taste of sugar"},
  {word:"sound", hint:"You hear it"},
  {word:"world", hint:"Earth and people"},
  {word:"plant", hint:"Grows in soil"},
  {word:"dream", hint:"You see while sleeping"},
  {word:"heart", hint:"Pumps blood"},
  {word:"laugh", hint:"Opposite of cry"},
  {word:"peace", hint:"No war"},
  {word:"music", hint:"You listen to it"},
  {word:"bread", hint:"Food from bakery"},
  {word:"clock", hint:"Shows time"},
  {word:"glass", hint:"You drink from it"},
  {word:"river", hint:"Water flows"},
  {word:"beach", hint:"Sand and sea"},
  {word:"cloud", hint:"In the sky"},
  {word:"phone", hint:"You call with it"},
  {word:"pencil", hint:"Used for writing"},
  {word:"window", hint:"You see through it"}
],

medium: [
  {word:"ability", hint:"Skill or talent"},
  {word:"academy", hint:"Place to learn"},
  {word:"account", hint:"Used for login"},
  {word:"achieve", hint:"Reach a goal"},
  {word:"advance", hint:"Move forward"},
  {word:"airport", hint:"Planes take off here"},
  {word:"balance", hint:"Not falling"},
  {word:"battery", hint:"Gives power"},
  {word:"because", hint:"Shows reason"},
  {word:"believe", hint:"Trust something"},
  {word:"benefit", hint:"Good advantage"},
  {word:"central", hint:"In the middle"},
  {word:"chicken", hint:"A common food"},
  {word:"climate", hint:"Weather conditions"},
  {word:"collect", hint:"Gather things"},
  {word:"college", hint:"Higher education"},
  {word:"combine", hint:"Join together"},
  {word:"comfort", hint:"Feeling relaxed"},
  {word:"command", hint:"Instruction to system"},
  {word:"company", hint:"Business organization"},
  {word:"compare", hint:"Find differences"},
  {word:"complex", hint:"Not simple"},
  {word:"concept", hint:"Idea or thought"},
  {word:"concern", hint:"Something important"},
  {word:"control", hint:"Have power over"},
  {word:"current", hint:"Happening now"},
  {word:"develop", hint:"Create or build"},
  {word:"digital", hint:"Opposite of analog"},
  {word:"display", hint:"Show on screen"},
  {word:"dynamic", hint:"Always changing"},
  {word:"example", hint:"Used to explain"},
  {word:"freedom", hint:"Opposite of control"},
  {word:"general", hint:"Common or broad"},
  {word:"imagine", hint:"Create in mind"},
  {word:"improve", hint:"Make better"},
  {word:"include", hint:"Contain"},
  {word:"machine", hint:"Mechanical device"},
  {word:"manager", hint:"Leads a team"},
  {word:"measure", hint:"Find size"},
  {word:"message", hint:"Send text"},
  {word:"natural", hint:"From nature"},
  {word:"network", hint:"Connected system"},
  {word:"process", hint:"Series of steps"},
  {word:"project", hint:"Work to complete"},
  {word:"science", hint:"Study of nature"},
  {word:"support", hint:"Help someone"},
  {word:"teacher", hint:"Teaches students"},
  {word:"traffic", hint:"Cars on road"},
  {word:"weather", hint:"Rain or sun"}
],

hard: [
  {word:"assembly", hint:"Low level programming"},
  {word:"browser", hint:"Used to surf internet"},
  {word:"compile", hint:"Convert code to machine"},
  {word:"complex", hint:"Not simple"},
  {word:"concept", hint:"Abstract idea"},
  {word:"context", hint:"Environment of code"},
  {word:"counter", hint:"Counts numbers"},
  {word:"default", hint:"Pre-selected option"},
  {word:"density", hint:"Mass per volume"},
  {word:"desktop", hint:"Computer screen"},
  {word:"diamond", hint:"Very hard gem"},
  {word:"display", hint:"Show visually"},
  {word:"dynamic", hint:"Changes frequently"},
  {word:"element", hint:"Part of system"},
  {word:"feature", hint:"Special function"},
  {word:"framework", hint:"React is one"},
  {word:"function", hint:"Reusable code block"},
  {word:"graphic", hint:"Visual design"},
  {word:"history", hint:"Past events"},
  {word:"initial", hint:"Beginning state"},
  {word:"library", hint:"Collection of code"},
  {word:"logical", hint:"Based on logic"},
  {word:"monitor", hint:"Computer screen"},
  {word:"network", hint:"Connected computers"},
  {word:"package", hint:"Install with npm"},
  {word:"program", hint:"Written code"},
  {word:"reactjs", hint:"Popular JS library"},
  {word:"resolve", hint:"Fix problem"},
  {word:"science", hint:"Study and research"},
  {word:"session", hint:"Login period"},
  {word:"storage", hint:"Save data"},
  {word:"stretch", hint:"Extend"},
  {word:"theorem", hint:"Math proof"},
  {word:"version", hint:"Software update"},
  {word:"virtual", hint:"Not physical"},
  {word:"website", hint:"Page on internet"}
]

};
